# -*- coding: utf-8 -*-
"""fizz_buzz.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FiULdJssF-W3b4do-0GHCL-ZQ0tl1q61
"""

def fb(n):
  '''
  divisible by 3        ->  Fizz
  divisible by 5        ->  Buzz
  divisible by 3 and 5  ->  FizzBuzz
  '''
  a = ''
  if n % 3 == 0:
    a += "Fizz"
  else:
    a = a
  if n % 5 == 0:
    a += "Buzz"
  else:
    a = a
  return a

i = 1
while i <= 20:
 print(i, fb(i))
 i = i + 1

